// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEHAmlnR3e2DTvH_fuZBJgpTSmEk4DfLY',
    appId: '1:10526612498:web:aa340d7137ef26f0e9cccb',
    messagingSenderId: '10526612498',
    projectId: 'hotelrisma-434d0',
    authDomain: 'hotelrisma-434d0.firebaseapp.com',
    storageBucket: 'hotelrisma-434d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNkkRnHR1cmPG6ObRPQmbaaGBZhKOkRBY',
    appId: '1:10526612498:android:1e00025dcdb317dce9cccb',
    messagingSenderId: '10526612498',
    projectId: 'hotelrisma-434d0',
    storageBucket: 'hotelrisma-434d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFo7YfepOevsHFa0hvwXITXD6JU0GutCQ',
    appId: '1:10526612498:ios:758a7fb6653262b7e9cccb',
    messagingSenderId: '10526612498',
    projectId: 'hotelrisma-434d0',
    storageBucket: 'hotelrisma-434d0.appspot.com',
    iosClientId: '10526612498-16pf58e62t0fms7kiidt7mvqnf73i4l4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookinghotel',
  );
}
